#!/bin/bash

while (( "$#" )); do
	case ${1} in
	-s|--sysroot)
                shift
		test -z "${1:-}" && echo "--sysroot specified without SYSROOT path." && exit 1
                SYSROOT="${1}"
		;;
        -a|--arch)
                shift
 		test -z "${1:-}" && echo "--arch specified without architecture." && exit 1
                ARCH="${1}"
                ;; 
        -h|--help)
                cat <<-EOF
					$0 -s <sysroot> [parameters]

					-a --arch:      Optional. Specify architecture tuple. Default: arm-linux-gnueabihf.
					-s --sysroot:   Mandatory. Specify SYSROOT path.
					-h --help:      This message.
				EOF
                exit 0
                ;;             
	esac
	shift
done

test -z "${SYSROOT:-}" && echo "SYSROOT not set" && exit 1
test -z "${ARCH:-}" && ARCH="arm-linux-gnueabihf"

echo "SYSROOT: ${SYSROOT}"
echo

for i in $(find -L ${SYSROOT}/usr/lib/${ARCH} -lname "/lib/${ARCH}*");
do
        echo -n "Relinking $i... "
        sudo ln -f -s ../../..$(readlink $i) $i
        echo "done."
done
