#!/bin/bash
test -f "$0.conf" && . $0.conf

SYSROOTUTILS_PATH=$(dirname $(realpath ${0}))

test -z ${C_PREFIX:-} && echo "C_PREFIX not set. Look at $0.conf and include it or set an environment variable" && exit 1
test -z ${CT_HOME:-} && CT_HOME=/opt/x-tools

CT_PATH=${CT_HOME}/${C_PREFIX::-1}/bin
SYSROOT="${SYSROOTUTILS_PATH}/sysrootutils/${DISTRO_NAME}/${DISTRO_VER}/${DISTRO_ARCH}"

while (( "$#" )); do
	case ${1} in
	-dummy)
		CONFIG=ONLY_PATH
		;;
	*)
		SYSROOT="${1}"
		;;
	esac
	shift
done

export SYSROOT
export PATH=${CT_PATH}:${PATH}

echo
echo "SYSROOT:		${SYSROOT}"
echo
echo "CT_PATH:		${CT_PATH}"

if [ "x$CONFIG" != "xONLY_PATH" ]
then
    export CC=${C_PREFIX}gcc
    export CPP=${C_PREFIX}cpp
    export CXX=${C_PREFIX}g++
    export CFLAGS="${CFLAGS} --sysroot ${SYSROOT}"
    export CFLAGS="${CFLAGS} -I${SYSROOT}/usr/include/${DISTRO_ARCH}"
    export CXXFLAGS="${CFLAGS}"
    export LDFLAGS="-L${SYSROOT}/usr/lib"
    export LDFLAGS="${LDFLAGS} -L${SYSROOT}/lib"
    export LDFLAGS="${LDFLAGS} -L${SYSROOT}/usr/lib/${DISTRO_ARCH}"
    export LDFLAGS="${LDFLAGS} -L${SYSROOT}/lib/${DISTRO_ARCH}"
    export LDFLAGS="${LDFLAGS} -Wl,-rpath-link ${SYSROOT}/usr/lib"
    export LDFLAGS="${LDFLAGS} -Wl,-rpath-link ${SYSROOT}/lib"
    export LDFLAGS="${LDFLAGS} -Wl,-rpath-link ${SYSROOT}/usr/lib/${DISTRO_ARCH}"
    export LDFLAGS="${LDFLAGS} -Wl,-rpath-link ${SYSROOT}/lib/${DISTRO_ARCH}"

    export PKG_CONFIG_DIR=
    export PKG_CONFIG_SYSROOT_DIR=${SYSROOT}
    export PKG_CONFIG_LIBDIR=${SYSROOT}/usr/lib/arm-linux-gnueabihf/pkgconfig:${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig

    export LD_LIBRARY_PATH="${SYSROOT}/usr/lib/${DISTRO_ARCH}:${SYSROOT}/lib/${DISTRO_ARCH}"
fi
echo
echo "CC: 			${CC}"
echo "CFLAGS: 		${CFLAGS}"
echo
echo "CXX: 			${CXX}"
echo "CXXFLAGS: 		${CXXFLAGS}"
echo
echo "LDFLAGS: 		${LDFLAGS}"
echo
echo "PKG_CONFIG_LIBDIR: 	${PKG_CONFIG_LIBDIR}"
echo "PKG_CONFIG_SYSROOT_DIR: ${PKG_CONFIG_SYSROOT_DIR}"
echo
echo "LD_LIBRARY_PATH:	${LD_LIBRARY_PATH}"
echo
echo "CT_XLDD_ROOT: 		${CT_XLDD_ROOT}"
echo
echo "Starting nested bash shell. Run exit or CTRL+D to return to the main shell"
echo
bash
